//
//  PhpHelper.swift
//  PHP Monitor
//
//  Created by Nico Verbruggen on 17/03/2022.
//  Copyright © 2025 Nico Verbruggen. All rights reserved.
//

import Foundation

class PhpHelper {
    static let keyPhrase = "This file was automatically generated by PHP Monitor."
    static let helperDirectorySuffix = ".config/phpmon/bin"
    static let symlinkDirectory = "/usr/local/bin"

    struct HelperFile {
        let version: String
        let dotless: String
        let destination: String
        let content: String
    }

    @discardableResult
    public static func regenerate(
        _ container: Container,
        installedVersions: Set<String>
    ) async -> [String] {
        let helperDirectory = helperDirectory(for: container)

        guard ensureHelperDirectoryExists(container, helperDirectory: helperDirectory) else {
            return []
        }

        let helperFiles = Constants.DetectedPhpVersions
            .sorted(by: { $0.versionCompare($1) == .orderedDescending })
            .map { version in
                makeHelperFile(
                    container,
                    version: version,
                    installed: installedVersions.contains(version)
                )
            }

        var writtenFiles: [String] = []

        for file in helperFiles {
            do {
                if try writeIfNeeded(container, file: file) {
                    writtenFiles.append(file.destination)
                }
            } catch {
                Log.err(error)
                Log.err("Could not write PHP Monitor helper for PHP \(file.version) to \(file.destination).")
            }
        }

        if shouldCreateSymlinks(container, helperDirectory: helperDirectory) {
            await createSymlinks(container, files: helperFiles)
        }

        return writtenFiles
    }

    private static func helperDirectory(for container: Container) -> String {
        return "\(container.paths.homePath)/\(helperDirectorySuffix)"
    }

    private static func helperDestination(for container: Container, dotless: String) -> String {
        return "\(helperDirectory(for: container))/pm\(dotless)"
    }

    private static func usesFishShell(_ container: Container) -> Bool {
        return container.paths.shell.contains("/fish")
    }

    private static func unavailableMessage(for version: String) -> String {
        return "Error: PHP \(version) is not installed. (You can install it via PHP Monitor to update this helper file.)"
    }

    private static func installedScript(
        _ container: Container,
        path: String,
        version: String,
        dotless: String
    ) -> String {
        return usesFishShell(container)
            ? fishInstalledScript(container, path, version, dotless)
            : zshInstalledScript(path, version, dotless)
    }

    private static func unavailableScript(
        _ container: Container,
        version: String
    ) -> String {
        return usesFishShell(container)
            ? fishUnavailableScript(container, version)
            : zshUnavailableScript(version)
    }

    private static func zshInstalledScript(
        _ path: String,
        _ version: String,
        _ dotless: String
    ) -> String {
        return """
            #!/bin/zsh
            # \(keyPhrase)
            # It reflects the location of PHP \(version)'s binaries on your system.
            # Usage: . pm\(dotless)
            [[ $ZSH_EVAL_CONTEXT =~ :file$ ]] \\
                && echo "PHP Monitor has enabled this terminal to use PHP \(version)." \\
                || echo "You must run '. pm\(dotless)' (or 'source pm\(dotless)') instead!";
            export PATH=\(path):$PATH
            """
    }

    private static func zshUnavailableScript(_ version: String) -> String {
        let message = unavailableMessage(for: version)

        return """
            #!/bin/zsh
            # \(keyPhrase)
            # This helper reflects that PHP \(version) is currently not installed.
            echo "\(message)"
            return 1 2>/dev/null || exit 1
            """
    }

    private static func fishInstalledScript(
        _ container: Container,
        _ path: String,
        _ version: String,
        _ dotless: String
    ) -> String {
        return """
            #!\(container.paths.binPath)/fish
            # \(keyPhrase)
            # It reflects the location of PHP \(version)'s binaries on your system.
            # Usage: . pm\(dotless)
            echo "PHP Monitor has enabled this terminal to use PHP \(version)."; \\
            set -x PATH \(path) $PATH
            """
    }

    private static func fishUnavailableScript(_ container: Container, _ version: String) -> String {
        let message = unavailableMessage(for: version)

        return """
            #!\(container.paths.binPath)/fish
            # \(keyPhrase)
            # This helper reflects that PHP \(version) is currently not installed.
            echo "\(message)"
            return 1
            """
    }

    private static func makeHelperFile(
        _ container: Container,
        version: String,
        installed: Bool
    ) -> HelperFile {
        let dotless = version.replacing(".", with: "")
        let destination = helperDestination(for: container, dotless: dotless)

        let content: String
        if installed {
            let path = URL(fileURLWithPath: "\(container.paths.optPath)/php@\(version)/bin")
                .resolvingSymlinksInPath().path

            content = installedScript(container, path: path, version: version, dotless: dotless)
        } else {
            content = unavailableScript(container, version: version)
        }

        return HelperFile(
            version: version,
            dotless: dotless,
            destination: destination,
            content: content
        )
    }

    private static func writeIfNeeded(
        _ container: Container,
        file: HelperFile
    ) throws -> Bool {
        let existingContents = container.filesystem.fileExists(file.destination)
            ? try? container.filesystem.getStringFromFile(file.destination)
            : nil

        if existingContents != file.content {
            try container.filesystem.writeAtomicallyToFile(file.destination, content: file.content)
        }

        if !container.filesystem.isExecutableFile(file.destination) {
            try container.filesystem.makeExecutable(file.destination)
        }

        return existingContents != file.content
    }

    private static func ensureHelperDirectoryExists(
        _ container: Container,
        helperDirectory: String
    ) -> Bool {
        do {
            if !container.filesystem.directoryExists(helperDirectory) {
                try container.filesystem.createDirectory(
                    helperDirectory,
                    withIntermediateDirectories: true
                )
            }

            return true
        } catch {
            Log.err(error)
            Log.err("Could not create the PHP Monitor helper directory at \(helperDirectory).")
            return false
        }
    }

    private static func shouldCreateSymlinks(
        _ container: Container,
        helperDirectory: String
    ) -> Bool {
        if container.shell.PATH.contains(helperDirectory) {
            return false
        }

        if !container.filesystem.isWriteableFile("\(symlinkDirectory)/") {
            Log.err("PHP Monitor does not have permission to symlink helpers in `\(symlinkDirectory)`.")
            return false
        }

        return true
    }

    private static func createSymlinks(
        _ container: Container,
        files: [HelperFile]
    ) async {
        for file in files {
            await createSymlink(container, dotless: file.dotless)
        }
    }

    private static func createSymlink(
        _ container: Container,
        dotless: String
    ) async {
        let source = helperDestination(for: container, dotless: dotless)
        let destination = "\(symlinkDirectory)/pm\(dotless)"

        if !container.filesystem.fileExists(destination) {
            Log.info("Creating new symlink: \(destination)")
            await container.shell.pipe("ln -s \(source) \(destination)")
            return
        }

        if !container.filesystem.isSymlink(destination) {
            Log.info("Overwriting existing file with new symlink: \(destination)")
            await container.shell.pipe("ln -fs \(source) \(destination)")
            return
        }

        Log.info("Symlink in \(destination) already exists, OK.")
    }
}
