//
//  PhpHelper+Templates.swift
//  PHP Monitor
//
//  Created by Nico Verbruggen on 27/04/2026.
//  Copyright © 2026 Nico Verbruggen. All rights reserved.
//

extension PhpHelper {
    private static let keyPhrase = "This file was automatically generated by PHP Monitor."

    enum HelperShell {
        case zsh
        case bash
        case fish

        static func detect(for container: Container) -> HelperShell {
            let shell = container.paths.shell

            if shell.contains("/fish") {
                return .fish
            }

            if shell.contains("/bash") {
                return .bash
            }

            return .zsh
        }

        func installedScript(
            _ container: Container,
            path: String,
            version: String,
            dotless: String
        ) -> String {
            return PhpHelper.makeInstalledScript(
                shebang: shebang(for: container),
                version: version,
                dotless: dotless,
                activationMessage: activationMessage(version: version, dotless: dotless),
                pathMutation: pathMutation(path: path)
            )
        }

        func unavailableScript(
            _ container: Container,
            version: String
        ) -> String {
            return PhpHelper.makeUnavailableScript(
                shebang: shebang(for: container),
                version: version,
                unavailableMessage: PhpHelper.unavailableMessage(for: version),
                failureReturn: failureReturn
            )
        }

        private func shebang(for container: Container) -> String {
            switch self {
            case .zsh:
                return "#!/bin/zsh"
            case .bash:
                return "#!/bin/bash"
            case .fish:
                return "#!\(container.paths.binPath)/fish"
            }
        }

        private func activationMessage(version: String, dotless: String) -> String {
            switch self {
            case .zsh:
                return """
                    [[ $ZSH_EVAL_CONTEXT =~ :file$ ]] \\
                        && echo "PHP Monitor has enabled this terminal to use PHP \(version)." \\
                        || echo "You must run '. pm\(dotless)' (or 'source pm\(dotless)') instead!";
                    """
            case .bash:
                return """
                    if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
                        echo "PHP Monitor has enabled this terminal to use PHP \(version)."
                    else
                        echo "You must run '. pm\(dotless)' (or 'source pm\(dotless)') instead!"
                    fi
                    """
            case .fish:
                return "echo \"PHP Monitor has enabled this terminal to use PHP \(version).\"; \\\""
            }
        }

        private func pathMutation(path: String) -> String {
            switch self {
            case .zsh, .bash:
                return "export PATH=\(path):$PATH"
            case .fish:
                return "set -x PATH \(path) $PATH"
            }
        }

        private var failureReturn: String {
            switch self {
            case .zsh, .bash:
                return "return 1 2>/dev/null || exit 1"
            case .fish:
                return "return 1"
            }
        }
    }

    private static func unavailableMessage(for version: String) -> String {
        return "Error: PHP \(version) is not installed. (You can install it via PHP Monitor to update this helper file.)"
    }

    private static func makeInstalledScript(
        shebang: String,
        version: String,
        dotless: String,
        activationMessage: String,
        pathMutation: String
    ) -> String {
        return """
            \(shebang)
            # \(keyPhrase)
            # It reflects the location of PHP \(version)'s binaries on your system.
            # Usage: . pm\(dotless)
            \(activationMessage)
            \(pathMutation)
            """
    }

    private static func makeUnavailableScript(
        shebang: String,
        version: String,
        unavailableMessage: String,
        failureReturn: String
    ) -> String {
        return """
            \(shebang)
            # \(keyPhrase)
            # This helper reflects that PHP \(version) is currently not installed.
            echo "\(unavailableMessage)"
            \(failureReturn)
            """
    }
}
