//
//  PhpHelper+Templates.swift
//  PHP Monitor
//
//  Created by Nico Verbruggen on 27/04/2026.
//  Copyright © 2026 Nico Verbruggen. All rights reserved.
//

extension PhpHelper {

    struct ShellTemplate {
        let shebang: (Container) -> String
        let activationMessage: (String, String) -> String
        let pathMutation: (String) -> String
        let failureReturn: String
    }

    enum HelperShell {
        case zsh
        case bash
        case fish

        static func detect(for container: Container) -> HelperShell {
            let shell = container.paths.shell

            if shell.contains("/fish") {
                return .fish
            }

            if shell.contains("/bash") {
                return .bash
            }

            return .zsh
        }

        func installedScript(
            _ container: Container,
            path: String,
            version: String,
            dotless: String
        ) -> String {
            let template = shellTemplate

            return PhpHelper.makeInstalledScript(
                shebang: template.shebang(container),
                version: version,
                dotless: dotless,
                activationMessage: template.activationMessage(version, dotless),
                pathMutation: template.pathMutation(path)
            )
        }

        func unavailableScript(
            _ container: Container,
            version: String
        ) -> String {
            let template = shellTemplate

            return PhpHelper.makeUnavailableScript(
                shebang: template.shebang(container),
                version: version,
                unavailableMessage: PhpHelper.unavailableMessage(for: version),
                failureReturn: template.failureReturn
            )
        }

        private var shellTemplate: ShellTemplate {
            switch self {
            case .zsh:
                return ShellTemplate(
                    shebang: { _ in "#!/bin/zsh" },
                    activationMessage: { version, dotless in
                        """
                            [[ $ZSH_EVAL_CONTEXT =~ :file$ ]] \\
                                && echo "PHP Monitor has enabled this terminal to use PHP \(version)." \\
                                || echo "You must run '. pm\(dotless)' (or 'source pm\(dotless)') instead!";
                            """
                    },
                    pathMutation: { path in "export PATH=\(path):$PATH" },
                    failureReturn: "return 1 2>/dev/null || exit 1"
                )
            case .bash:
                return ShellTemplate(
                    shebang: { _ in "#!/bin/bash" },
                    activationMessage: { version, dotless in
                        """
                            if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
                                echo "PHP Monitor has enabled this terminal to use PHP \(version)."
                            else
                                echo "You must run '. pm\(dotless)' (or 'source pm\(dotless)') instead!"
                            fi
                            """
                    },
                    pathMutation: { path in "export PATH=\(path):$PATH" },
                    failureReturn: "return 1 2>/dev/null || exit 1"
                )
            case .fish:
                return ShellTemplate(
                    shebang: { container in "#!\(container.paths.binPath)/fish" },
                    activationMessage: { version, _ in
                        "echo \"PHP Monitor has enabled this terminal to use PHP \(version).\"; \\\""
                    },
                    pathMutation: { path in "set -x PATH \(path) $PATH" },
                    failureReturn: "return 1"
                )
            }
        }
    }

    // MARK: Strings

    static let keyPhrase = "This file was automatically generated by PHP Monitor."
    private static let locationPhrase = "This helper reflects the location of PHP binaries on your system."
    private static let notFoundPhrase = "This helper reflects that a version of PHP is currently not installed."

    private static func unavailableMessage(for version: String) -> String {
        return "Error: PHP \(version) is not installed. (You can install it via PHP Monitor to update this helper file.)"
    }

    // MARK: Script Creation

    private static func makeInstalledScript(
        shebang: String,
        version: String,
        dotless: String,
        activationMessage: String,
        pathMutation: String
    ) -> String {
        return """
            \(shebang)
            # \(keyPhrase)
            # \(locationPhrase)
            # Usage: . pm\(dotless)
            \(activationMessage)
            \(pathMutation)
            """
    }

    private static func makeUnavailableScript(
        shebang: String,
        version: String,
        unavailableMessage: String,
        failureReturn: String
    ) -> String {
        return """
            \(shebang)
            # \(keyPhrase)
            # \(notFoundPhrase)
            echo "\(unavailableMessage)"
            \(failureReturn)
            """
    }
}
