//
//  PhpHelper.swift
//  PHP Monitor
//
//  Created by Nico Verbruggen on 17/03/2022.
//  Copyright © 2025 Nico Verbruggen. All rights reserved.
//

import Foundation

// TODO: This file is a little too big right now, it needs to be cleaned up

class PhpHelper {
    static let keyPhrase = "This file was automatically generated by PHP Monitor."
    static let helperDirectorySuffix = ".config/phpmon/bin"
    static let symlinkDirectory = "/usr/local/bin"

    struct HelperFile {
        let version: String
        let dotless: String
        let destination: String
        let content: String
    }

    @discardableResult
    public static func regenerate(
        _ container: Container,
        installedVersions: Set<String>
    ) async -> [String] {
        let helperDirectory = helperDirectory(for: container)

        guard ensureHelperDirectoryExists(container, helperDirectory: helperDirectory) else {
            return []
        }

        let helperFiles = Constants.DetectedPhpVersions
            .sorted(by: { $0.versionCompare($1) == .orderedDescending })
            .map { version in
                makeHelperFile(
                    container,
                    version: version,
                    installed: installedVersions.contains(version)
                )
            }

        var writtenFiles: [String] = []

        for file in helperFiles {
            do {
                if try writeIfNeeded(container, file: file) {
                    writtenFiles.append(file.destination)
                }
            } catch {
                Log.err(error)
                Log.err("Could not write PHP Monitor helper for PHP \(file.version) to \(file.destination).")
            }
        }

        if shouldCreateSymlinks(container, helperDirectory: helperDirectory) {
            await createSymlinks(container, files: helperFiles)
        }

        return writtenFiles
    }

    static func helperDirectory(for container: Container) -> String {
        return "\(container.paths.homePath)/\(helperDirectorySuffix)"
    }

    static func helperDestination(for container: Container, dotless: String) -> String {
        return "\(helperDirectory(for: container))/pm\(dotless)"
    }

    private static func usesFishShell(_ container: Container) -> Bool {
        return container.paths.shell.contains("/fish")
    }

    private static func installedScript(
        _ container: Container,
        path: String,
        version: String,
        dotless: String
    ) -> String {
        return usesFishShell(container)
            ? Fish.installedScript(container, path, version, dotless)
            : Zsh.installedScript(path, version, dotless)
    }

    private static func unavailableScript(
        _ container: Container,
        version: String
    ) -> String {
        return usesFishShell(container)
            ? Fish.unavailableScript(container, version)
            : Zsh.unavailableScript(version)
    }

    private static func makeHelperFile(
        _ container: Container,
        version: String,
        installed: Bool
    ) -> HelperFile {
        let dotless = version.replacing(".", with: "")
        let destination = helperDestination(for: container, dotless: dotless)

        let content: String
        if installed {
            let path = URL(fileURLWithPath: "\(container.paths.optPath)/php@\(version)/bin")
                .resolvingSymlinksInPath().path

            content = installedScript(container, path: path, version: version, dotless: dotless)
        } else {
            content = unavailableScript(container, version: version)
        }

        return HelperFile(
            version: version,
            dotless: dotless,
            destination: destination,
            content: content
        )
    }

    private static func writeIfNeeded(
        _ container: Container,
        file: HelperFile
    ) throws -> Bool {
        let existingContents = container.filesystem.fileExists(file.destination)
            ? try? container.filesystem.getStringFromFile(file.destination)
            : nil

        if existingContents != file.content {
            try container.filesystem.writeAtomicallyToFile(file.destination, content: file.content)
        }

        if !container.filesystem.isExecutableFile(file.destination) {
            try container.filesystem.makeExecutable(file.destination)
        }

        return existingContents != file.content
    }

    private static func ensureHelperDirectoryExists(
        _ container: Container,
        helperDirectory: String
    ) -> Bool {
        do {
            if !container.filesystem.directoryExists(helperDirectory) {
                try container.filesystem.createDirectory(
                    helperDirectory,
                    withIntermediateDirectories: true
                )
            }

            return true
        } catch {
            Log.err(error)
            Log.err("Could not create the PHP Monitor helper directory at \(helperDirectory).")
            return false
        }
    }
}
